# Generated by Django 6.0.6 on 2026-07-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='phone',
            field=models.CharField(default=2233445566, max_length=15),
            preserve_default=False,
        ),
    ]
