# Generated by Django 6.0.6 on 2026-07-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default=1122334455, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
