# Generated by Django 6.0.6 on 2026-07-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.CharField(default='Unknown Hospital', max_length=100),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='reason',
            field=models.TextField(default='No Reason'),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
