# Generated by Django 6.0.6 on 2026-07-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0002_bloodrequest_hospital_bloodrequest_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodstock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
